project:
  type: website

website:
  title: "Lucy's adventures in science"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: research.qmd
        text: "My Research"

format:
  html:
    theme: lux
    css: styles.css
    toc: true
